server:
  port: 8082

spring:
  application:
   name: bank-account

  datasource:
    url: jdbc:h2:file:./data/db;DATABASE_TO_UPPER=false
    #url: jdbc:h2:mem:bank_account_db;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:

    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Cria e atualiza as tabelas automaticamente

  h2:
    console:
      enabled: true  # Habilita o console web do H2
      path: /h2-console  # Caminho do console

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
          datasource:
            init:
              ScriptUtils: DEBUG
